version: "3.8"

services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    user: node
    volumes:
      - ..:/workspace:cached
      - node_modules:/workspace/node_modules
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=development
    command: sleep infinity
    networks:
      - barcode-network
    container_name: bar-code-gen

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - barcode-network

volumes:
  node_modules:
  mongodb_data:

networks:
  barcode-network:
    driver: bridge